# Project files
file(GLOB HEADERS "src/*.hpp" "src/*.h")
file(GLOB SOURCES "src/*.cpp")
file(GLOB UIFILES "src/*.ui")
set(
    PROJECT_FILES
    ${HEADERS} ${SOURCES} ${UIFILES} ${RESOURCES_COMMONFILE}
)

set(
    PROJECT_LINK_LIBS
    Qt${QT_VERSION_MAJOR}::Core
    Qt${QT_VERSION_MAJOR}::Widgets
    Qt${QT_VERSION_MAJOR}::Gui
)

# Main target
set( PROJECT_RELEASE_TGT ${PROJECT_NAME}.bin )
add_executable( ${PROJECT_RELEASE_TGT} )
target_sources(${PROJECT_RELEASE_TGT} PRIVATE ${PROJECT_FILES})
target_link_libraries( ${PROJECT_RELEASE_TGT} PRIVATE ${PROJECT_LINK_LIBS} )
LINK_TARGET_LIBRARY(${PROJECT_RELEASE_TGT} Logger)
LINK_TARGET_LIBRARY(${PROJECT_RELEASE_TGT} Common)
LINK_TARGET_LIBRARY(${PROJECT_RELEASE_TGT} Qt-Custom)
LINK_TARGET_LIBRARY(${PROJECT_RELEASE_TGT} Encryption)
LINK_TARGET_LIBRARY(${PROJECT_RELEASE_TGT} EditorForm)
LINK_TARGET_LIBRARY(${PROJECT_RELEASE_TGT} PluginModule)
CONFIGURE_SUFFIX(${PROJECT_RELEASE_TGT} ".DEBUG" "")
set_target_properties(
    ${PROJECT_RELEASE_TGT} PROPERTIES
    BUILD_WITH_INSTALL_RPATH TRUE
    INSTALL_RPATH_USE_LINK_PATH TRUE
    INSTALL_RPATH "./lib;../lib"
)

# ======================================== #
# Installation
install(TARGETS ${PROJECT_RELEASE_TGT}
    RUNTIME     DESTINATION ${INSTALL_DESTINATION_PREFIX}
    LIBRARY     DESTINATION ${INSTALL_DESTINATION_PREFIX}/lib
    ARCHIVE     DESTINATION ${INSTALL_DESTINATION_PREFIX}/lib/static
    INCLUDES    DESTINATION ${INSTALL_DESTINATION_PREFIX}/include
)

set(
    PROJECT_DISABLE_EXECUTABLE ON
)

# Packet creation
include(InstallRequiredSystemLibraries)

set(
    PROJECT_INSTALL_APPIMAGE ON
)
set(CPACK_PACKAGE_NAME ${INSTALL_BINARY_NAME}.pkg)
set(CPACK_PACKAGE_VERSION ${PROJECT_VERSION})

if (PROJECT_INSTALL_APPIMAGE)
    set(CPACK_GENERATOR "External")
    set(CPACK_EXTERNAL_ENABLED TRUE)
    set(CPACK_EXTERNAL_BUILT_PACKAGES "AppImage")
    set(CPACK_TOPLEVEL_TAG "AppImage")
    include(CPack)
else()
    set(CPACK_GENERATOR "DEB")
    set(CPACK_DEBIAN_PACKAGE_MAINTAINER "VinTRiZz")
    set(CPACK_PACKAGE_DIRECTORY ${INSTALL_DESTINATION_PREFIX})
    include(CPack)
endif()
